
platform :ios, '8.0'

target 'LSTPopView_Example' do
  pod 'LSTPopView', :path => '../'
  pod 'LSTCategory'
  pod 'Masonry'
  pod 'Bugly'

  target 'LSTPopView_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
